//----------------------------------------------------------------------------
// ObjectWindows - (C) Copyright 1991, 1993 by Borland International
//----------------------------------------------------------------------------

#define CM_THROTTLE       101
#define CM_CLUTCH         102
#define CM_BRAKE          103
#define CM_HANDBRAKE      104
#define CM_GEAR           105
#define CM_WHEELPOSITION  106
#define CM_IGNITION       107
#define CM_HEADPOSITION   108


