
//===================================================================================================================//
// constants used by the program
//===================================================================================================================//


#if !defined(CONST_H)
#define CONST_H

#include "TRIPLET.H"

// Angle of vision
#define KDistance 1000

// distance to the horizon
#define KHorizon  10000

// back mirror
#define BackMirrorW 200
#define BackMirrorH 100
// right mirror
#define RightMirrorW 100
#define RightMirrorH 100

#define Step         5

// car high
#define KCARHIGH     10

// ambient light
#define AMBIENT_LIGHT 100

// delay for the timer
#define DELAY_TIMER  20

#endif
