//REGEN_FILEHEADING
//REGEN_FILEHEADING

     /********************************************************************
      *                                                                  *
      *   Source File: PROJECT.h                                         *
      *   Description: Header file for PROJECT application               *
      *   Date:        Thu Feb 23 11:17:55 1995                          *
      *                                                                  *
      ********************************************************************/

#ifndef __PROJECT__H
#define __PROJECT__H

//REGEN_HEADER
//REGEN_HEADER


//REGEN_VARS
//REGEN_VARS



#endif // __PROJECT__H
