//REGEN_FILEHEADING
//REGEN_FILEHEADING

     /********************************************************************
      *                                                                  *
      *   Source File: PROJECls.h                                        *
      *   Description: Dialog Classes for PROJECT                        *
      *   Date:        Thu Feb 23 11:17:55 1995                          *
      *                                                                  *
      ********************************************************************/

#ifndef __PROJECTCLS__H
#define __PROJECTCLS__H

#include <owl.h>
#include <bwcc.h>
#include "PROJECID.H"

//REGEN_VARIABLES
//REGEN_VARIABLES

//REGEN_HEADER
//REGEN_HEADER

//REGEN_CLASSES
//REGEN_CLASSES

#endif // __PROJECTCLS_H

