//REGEN_FILEHEADING
//REGEN_FILEHEADING

     /********************************************************************
      *                                                                  *
      *   Source File: projecID.h                                        *
      *   Description: Header file IDS for project application           *
      *   Date:        Fri Mar 10 16:13:43 1995                          *
      *                                                                  *
      ********************************************************************/

#ifndef __PROJECTID__H
#define __PROJECTID__H

//REGEN_HEADER
//REGEN_HEADER

// Defines for menu item IDs
#define   IDM_MAP_SWAP                        101
#define   IDM_MAP_ZOOM_IN                     102
#define   IDM_MAP_ZOOM_OUT                    103
#define   IDM_LESS_DETAIL                     104
#define   IDM_MORE_DETAIL                     105
#define   IDM_COLOR_ON_OFF                    106
#define   IDM_LEFT                            107
#define   IDM_RIGHT                           108
#define   IDM_SPEED_UP                        109
#define   IDM_SPEED_DOWN                      110
#define   IDM_HEAD_RESET                      111
#define   IDM_HEAD_LEFT                       112
#define   IDM_HEAD_RIGHT                      113
#define   IDM_HELP                            114
#define   IDM_CONNECTION                      115
#define   IDM_MIRRORS                         116
#define   IDM_REPLAY                          117
#define   IDM_OPEN_FILE                       118
#define   IDM_BKMIRRORS_LEFT                  119
#define   IDM_BKMIRRORS_RIGHT                 120
#define   IDM_RTMIRRORS_LEFT                  121
#define   IDM_RTMIRRORS_RIGHT                 122
#define   IDM_TIMER                           200


#endif // __PROJECTID__H
