//===================================================================================================================//
// Triangle unit header
//===================================================================================================================//

#if !defined(TRIANGLE_H)
#define TRIANGLE_H

// clipping within a triangle

#include <math.h>
#include "triplet.h"

int Triangle(MyTriplet);

//int Triangle(POINT,POINT,POINT,MyTriplet);

#endif