//===================================================================================================================//
// View module header
//===================================================================================================================//

#if !defined(VIEW_H)
#define VIEW_H

#include <math.h>
#include "list.h"

void MyView(HDC,MyTriplet,OList *,float,float,float,POINT,POINT,short,short,short,MyTriplet);
void SpeedoMeter(HDC,long int,long int,short,short);

#endif